AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Deploy AppSync Private API in a VPC, provide the VPC ID and Subnet ID to deploy the AppSync VPC Interface Endpoints

Parameters:
  #### Parameter for VPC ID of the subnets to deploy the AppSync API Interface Endpoint ####
  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id
    ConstraintDescription: Must be a valid VPC ID.

  #### Parameter for SubnetIds to deploy the AppSync API Interface Endpoint ####
  SubnetIds:
    Description: Comma-separated list of Subnet IDs
    Type: List<AWS::EC2::Subnet::Id>
    ConstraintDescription: Must be a comma-separated list of valid Subnet IDs.

Resources:
  #### AppSync VPC Interface Endpoint ####
  AppSyncVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.appsync-api"
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      SubnetIds: !Ref SubnetIds
      SecurityGroupIds:
        - !Ref AppSyncVPCEndpointSecurityGroup
      PrivateDnsEnabled: true

  #### AppSync VPC Interface Endpoint Security Group, you can further restrict this security group to only the VPC or Subnet CIDR range ####
  AppSyncVPCEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for AppSync VPC Endpoint
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0 # Update for VPC CIDR range
      VpcId: !Ref VpcId

  #### DynamoDb Table ####
  RestaurantTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: restaurantId
        Type: String

  #### Appsync API ####
  AppsyncGraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub "RestaurantAPI-${AWS::StackName}"
      AuthenticationType: API_KEY
      LogConfig:
        ExcludeVerboseContent: false
        FieldLogLevel: "ALL"
        CloudWatchLogsRoleArn: !GetAtt AppsyncPushToCloudWatchLogsRole.Arn
      XrayEnabled: true
      Visibility: PRIVATE

  AppsyncGraphQLApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt AppsyncGraphQLApi.ApiId

  AppsyncGraphQLApiSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt AppsyncGraphQLApi.ApiId
      DefinitionS3Location: "./graphql/schema.graphql"

  #### Appsync API Logging ####

  AppsyncGraphQLApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/appsync/apis/${AppsyncGraphQLApi.ApiId}"
      RetentionInDays: 7

  AppsyncPushToCloudWatchLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - appsync.amazonaws.com
            Action:
              - sts:AssumeRole

  AppsyncPushToCloudWatchLogsRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AWS::StackName}-AppsyncPushToCloudWatchLogs-Policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !GetAtt AppsyncGraphQLApiLogGroup.Arn
      Roles:
        - !Ref AppsyncPushToCloudWatchLogsRole

  #### Appsync DynamoDB Datasource ####

  AppsyncDynamoDBDatasourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com

  AppsyncDynamoDBDatasourceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AWS::StackName}-AppsyncDynamoDB-Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:DeleteItem
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${RestaurantTable}"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${RestaurantTable}/*"
      Roles:
        - !Ref AppsyncDynamoDBDatasourceRole

  AppsyncGraphQLApiDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppsyncGraphQLApi.ApiId
      Name: "Restaurant_Api_Datasource"
      Type: "AMAZON_DYNAMODB"
      ServiceRoleArn: !GetAtt AppsyncDynamoDBDatasourceRole.Arn
      DynamoDBConfig:
        AwsRegion: !Sub "${AWS::Region}"
        TableName: !Ref RestaurantTable

  #### Appsync Resolvers ####
  GetRestaurantResolver:
    Type: AWS::AppSync::Resolver
    DependsOn:
      - AppsyncGraphQLApiSchema
    Properties:
      ApiId: !GetAtt AppsyncGraphQLApi.ApiId
      TypeName: Query
      FieldName: getRestaurant
      DataSourceName: !GetAtt AppsyncGraphQLApiDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: "1.0.0"
      CodeS3Location: resolvers/getRestaurant.js

  ListRestaurantsResolver:
    Type: AWS::AppSync::Resolver
    DependsOn:
      - AppsyncGraphQLApiSchema
    Properties:
      ApiId: !GetAtt AppsyncGraphQLApi.ApiId
      TypeName: Query
      FieldName: listRestaurants
      DataSourceName: !GetAtt AppsyncGraphQLApiDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: "1.0.0"
      CodeS3Location: resolvers/listRestaurants.js

  AddRestaurantResolver:
    Type: AWS::AppSync::Resolver
    DependsOn:
      - AppsyncGraphQLApiSchema
    Properties:
      ApiId: !GetAtt AppsyncGraphQLApi.ApiId
      TypeName: Mutation
      FieldName: addRestaurant
      DataSourceName: !GetAtt AppsyncGraphQLApiDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: "1.0.0"
      CodeS3Location: resolvers/addRestaurant.js

  DeleteRestaurantResolver:
    Type: AWS::AppSync::Resolver
    DependsOn:
      - AppsyncGraphQLApiSchema
    Properties:
      ApiId: !GetAtt AppsyncGraphQLApi.ApiId
      TypeName: Mutation
      FieldName: deleteRestaurant
      DataSourceName: !GetAtt AppsyncGraphQLApiDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: "1.0.0"
      CodeS3Location: resolvers/deleteRestaurant.js

  UpdateRestaurantResolver:
    Type: AWS::AppSync::Resolver
    DependsOn:
      - AppsyncGraphQLApiSchema
    Properties:
      ApiId: !GetAtt AppsyncGraphQLApi.ApiId
      TypeName: Mutation
      FieldName: updateRestaurant
      DataSourceName: !GetAtt AppsyncGraphQLApiDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: "1.0.0"
      CodeS3Location: resolvers/updateRestaurant.js

Outputs:
  AppSyncGraphQLAPIURL:
    Description: "AppSync GraphQL API URL"
    Value: !GetAtt AppsyncGraphQLApi.GraphQLUrl

  AppSyncApiKey:
    Description: "AppSync API Key"
    Value: !GetAtt AppsyncGraphQLApiKey.ApiKey

  AppSyncVPCEndpointDNS:
    Description: AppSync VPC Endpoint DNS
    Value: !Select
      - 1
      - !Split
        - ":"
        - !Select
          - 0
          - !GetAtt
            - AppSyncVPCEndpoint
            - DnsEntries
